app:
  image: busybox
  volumes:
    - .:/var/www
  tty: true

nginx:
  build: docker/nginx
  links:
    - php
  volumes_from:
    - app
  environment:
    VIRTUAL_HOST: spreq.dk

php:
  build: docker/php
  working_dir: /var/www/symfony/web
  links:
    - mysql
    - redis
  volumes_from:
    - app

composer:
  build: docker/composer
  working_dir: /var/www/symfony
  volumes_from:
    - app

mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: noop
    MYSQL_DATABASE: mydb
    MYSQL_USER: dbuser
    MYSQL_PASSWORD: dbpass

redis:
  image: redis:3.0

node:
  build: docker/node
  links:
    - redis
  volumes_from:
    - app
  expose:
    - 80
  environment:
    VIRTUAL_HOST: socket.spreq.dk
    DOCUMENT_ROOT: /var/www/node
